#!/bin/bash
# =============================================================================
# Script 5: Open Source Manifesto Generator
# Author   : Thakur Shubham Kumar
# Reg. No  : 24BEC10171
# Course   : Open Source Software (NGMC)
# Purpose  : Interactively collect user input and generate a personalised
#            open source philosophy statement, saved to a .txt file.
#
# Concepts demonstrated:
#   - read (interactive user input)
#   - String concatenation and variable interpolation
#   - Writing to a file with > and >>
#   - date command for timestamping
#   - Aliases concept (shown via comment and alias definition)
#   - Formatting and output design
# =============================================================================

# --- Alias demonstration (aliases make commands shorter/memorable) ---
# In a real interactive session you could run: alias today='date +%d-%m-%Y'
# Here we define the alias and use the underlying command in the script:
# alias today='date +%d-%B-%Y'   # Aliases don't expand in non-interactive scripts
FORMATTED_DATE=$(date '+%d %B %Y')    # We use command substitution instead
TIMESTAMP=$(date '+%Y%m%d_%H%M%S')   # For unique filename

echo "============================================================"
echo "         OPEN SOURCE MANIFESTO GENERATOR"
echo "  Student : Thakur Shubham Kumar | Reg: 24BEC10171"
echo "============================================================"
echo ""
echo "  Answer three questions to generate your personal"
echo "  open source philosophy manifesto."
echo ""
echo "  Your answers will be saved to a .txt file."
echo "------------------------------------------------------------"
echo ""

# --- Interactive input using 'read' ---
read -p "  1. Name one open-source tool you use every day: " TOOL
echo ""
read -p "  2. In one word, what does 'freedom' mean to you? " FREEDOM
echo ""
read -p "  3. Name one thing you would build and share freely: " BUILD
echo ""

# --- Validate inputs — make sure none are empty ---
if [ -z "$TOOL" ] || [ -z "$FREEDOM" ] || [ -z "$FREEDOM" ] || [ -z "$BUILD" ]; then
    echo "  ERROR: All three answers are required. Please run the script again."
    exit 1
fi

# --- Set output filename using current user + timestamp ---
OUTPUT="manifesto_$(whoami)_${TIMESTAMP}.txt"

# --- Compose the manifesto paragraph using string concatenation ---
# We build a multi-paragraph manifesto from the user's answers.

# Write the manifesto to file using > (overwrite) and >> (append)
# First line: overwrite/create the file
echo "============================================================" > "$OUTPUT"
echo "         MY OPEN SOURCE MANIFESTO" >> "$OUTPUT"
echo "  Generated by : Thakur Shubham Kumar (24BEC10171)" >> "$OUTPUT"
echo "  Date         : $FORMATTED_DATE" >> "$OUTPUT"
echo "============================================================" >> "$OUTPUT"
echo "" >> "$OUTPUT"

# --- Paragraph 1: Personal relationship with open source ---
echo "Every day, I rely on $TOOL — a tool that exists because someone, somewhere," >> "$OUTPUT"
echo "chose to write it openly and share it with the world. I did not pay for it." >> "$OUTPUT"
echo "I did not negotiate for it. It was simply there, freely available, because" >> "$OUTPUT"
echo "its creators believed that knowledge and tools belong to everyone." >> "$OUTPUT"
echo "" >> "$OUTPUT"

# --- Paragraph 2: What freedom means ---
echo "To me, freedom in the context of software means $FREEDOM. It is not just" >> "$OUTPUT"
echo "about price — it is about power. The power to read the code that runs my" >> "$OUTPUT"
echo "computer. The power to change it if it does not suit my needs. The power to" >> "$OUTPUT"
echo "share what I improve with others who might need it too. The Linux Kernel," >> "$OUTPUT"
echo "which I have studied in this course, embodies this freedom completely. Under" >> "$OUTPUT"
echo "the GPL v2, every line of code must remain open — no one can take it, lock" >> "$OUTPUT"
echo "it away, and sell it back to us without the source." >> "$OUTPUT"
echo "" >> "$OUTPUT"

# --- Paragraph 3: Commitment to build and share ---
echo "I commit to this philosophy. One day, I will build $BUILD — and when I do," >> "$OUTPUT"
echo "I will share it freely. Not because I have to. But because I understand, from" >> "$OUTPUT"
echo "studying projects like the Linux Kernel, that the greatest software in human" >> "$OUTPUT"
echo "history was not written for profit. It was written for curiosity, for necessity," >> "$OUTPUT"
echo "and for the belief that what one person builds can make life better for everyone." >> "$OUTPUT"
echo "" >> "$OUTPUT"

# --- Closing statement ---
echo "Standing on the shoulders of Linus Torvalds, Richard Stallman, and thousands" >> "$OUTPUT"
echo "of unnamed contributors, I choose to give back to the commons." >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "                              — Thakur Shubham Kumar" >> "$OUTPUT"
echo "                                24BEC10171, $(date '+%Y')" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "============================================================" >> "$OUTPUT"
echo "  [ Tool I use daily  : $TOOL ]" >> "$OUTPUT"
echo "  [ Freedom means     : $FREEDOM ]" >> "$OUTPUT"
echo "  [ I will build      : $BUILD ]" >> "$OUTPUT"
echo "============================================================" >> "$OUTPUT"

# --- Display the manifesto on screen ---
echo ""
echo "------------------------------------------------------------"
echo "  YOUR MANIFESTO (also saved to: $OUTPUT)"
echo "------------------------------------------------------------"
echo ""
cat "$OUTPUT"

echo ""
echo "  Manifesto saved successfully to: $OUTPUT"
echo "  Share it. It belongs to you — and to everyone."
echo "============================================================"
