#!/bin/bash
# ============================================================
# Script 5: Open Source Manifesto Generator
# Author: [Thakur Shubham Kumar] | Registration: [24BEC10171]
# Course: Open Source Software | Capstone Project
# Purpose: Interactively generate a personal OSS philosophy statement
# ============================================================

# --- Alias demonstration ---
# In a real interactive session, you could set:
#   alias generate_manifesto='bash script5_manifesto_generator.sh'
# Aliases make long commands shorter — a core Linux usability concept.
# Note: aliases are shell-session scoped; they don't persist across scripts.

# --- Define output file name using current username ---
OUTPUT="manifesto_thakur95124-svg.txt"

# --- Print welcome banner ---
echo "============================================"
echo "   Open Source Manifesto Generator"
echo "   OSS Capstone — VITyarthi"
echo "============================================"
echo ""
echo "  This tool will generate your personal open-source"
echo "  philosophy statement based on three questions."
echo "  Answer honestly — this is your declaration."
echo ""
echo "--------------------------------------------"

# --- Collect user input using read ---

# Question 1: A tool they use every day
read -p "  1. Name one open-source tool you use every day: " TOOL

# Validate: don't accept empty input
while [ -z "$TOOL" ]; do
    echo "  Please enter a tool name."
    read -p "  1. Name one open-source tool you use every day: " TOOL
done

# Question 2: What freedom means to them (one word)
read -p "  2. In one word, what does 'freedom' mean to you? " FREEDOM

# Validate: must be a single word (no spaces)
while [ -z "$FREEDOM" ]; do
    echo "  Please enter one word."
    read -p "  2. In one word, what does 'freedom' mean to you? " FREEDOM
done

# Question 3: Something they would build and share
read -p "  3. Name one thing you would build and share freely: " BUILD

# Validate: must not be empty
while [ -z "$BUILD" ]; do
    echo "  Please enter something you would build."
    read -p "  3. Name one thing you would build and share freely: " BUILD
done

echo ""
echo "--------------------------------------------"
echo "  Generating your manifesto..."
echo "--------------------------------------------"
echo ""

# --- Get current date in a readable format ---
DATE=30-03-2026

# --- Get the username for personalisation ---
USER_ID="thakur95124-svg"

# --- Compose the manifesto using string concatenation and echo >> ---
# The >> operator appends to the file (creates it if it doesn't exist)
# We first clear/create the file with >, then append paragraphs

# Write the header to the file
echo "============================================" > "$OUTPUT"
echo "   MY OPEN SOURCE MANIFESTO" >> "$OUTPUT"
echo "   Generated by: $USER_ID" >> "$OUTPUT"
echo "   Date: $DATE" >> "$OUTPUT"
echo "============================================" >> "$OUTPUT"
echo "" >> "$OUTPUT"

# Write the personalised manifesto paragraph
# String concatenation is done naturally in bash by placing variables inline
echo "I believe in the power of open software to change the world." >> "$OUTPUT"
echo "Every day, I rely on $TOOL — a tool built not for profit," >> "$OUTPUT"
echo "but for the love of craft and the belief that knowledge" >> "$OUTPUT"
echo "belongs to everyone. To me, freedom means $FREEDOM." >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "I understand now that the software I use was written by" >> "$OUTPUT"
echo "people who chose to share their work so that others could" >> "$OUTPUT"
echo "build on it. Linus Torvalds shared the Linux kernel." >> "$OUTPUT"
echo "Richard Stallman shared the GNU tools. Generations of" >> "$OUTPUT"
echo "developers gave their time freely — and because of that," >> "$OUTPUT"
echo "I have tools that no money could have built alone." >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "In the spirit of open source, I commit to building" >> "$OUTPUT"
echo "$BUILD and sharing it freely with the world." >> "$OUTPUT"
echo "Because the best way to honour the giants whose shoulders" >> "$OUTPUT"
echo "I stand on is to become a shoulder for someone else." >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "Signed: thakur95124-svg-web | $DATE" >> "$OUTPUT"
echo "============================================" >> "$OUTPUT"

# --- Confirm file was saved ---
echo "  Manifesto saved to: thakur95124-svg"
echo ""

# --- Display the generated manifesto ---
echo "============================================"
echo "   YOUR MANIFESTO:"
echo "============================================"
cat "$OUTPUT"
echo ""
echo "  [Tip: Share this file — open source starts with sharing]"
